apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask
commonLabels:
  app: flask
resources:
- ./deployment.yaml
- ./service.yaml
- ./namespace.yaml
images:
- name: eu.gcr.io/${PROJECT_NAME}/flask
  newTag: ${CIRCLE_SHA1}